### ISSUE TITLE
HTML-like labels not working

### ISSUE THREAD

**Issue by jjkavalam** [observablehq/graphviz#2]
HTML-like labels feature of Graphviz not working even though viz.js itself handles it well.

Please see https://beta.observablehq.com/@jjkavalam/graphviz for an example

**Comment by mbostock** [comment]
This feature requires the “full” renderer, whereas this library packages the “lite” renderer. You can load the full renderer yourself as described in this notebook, or import the notebook directly rather than using this helper library:

https://beta.observablehq.com/@mbostock/hello-viz-js
